const express = require('express');
const router = express.Router();
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const db = require('../db');
const { auth, checkRole, SECRET_KEY } = require('../authMiddleware');
const { logActivity } = require('../logger');

// Public departments list for signup (active only)
router.get('/departments-public', (req, res) => {
  const depts = db.read('departments')
    .filter(d => d.status === 'Active')
    .map(({ id, name, description }) => ({ id, name, description }));
  res.json(depts);
});

// Sign Up — creates Employee only, no role selection
router.post('/signup', (req, res) => {
  const { name, email, password, phone, departmentId } = req.body;

  if (!name || !email || !password) {
    return res.status(400).json({ message: 'Name, email and password are required fields.' });
  }

  // Check unique email
  const existingUser = db.findOne('users', { email: email.toLowerCase() });
  if (existingUser) {
    return res.status(400).json({ message: 'An account with this email address already exists.' });
  }

  // Validate department if provided
  if (departmentId) {
    const dept = db.findById('departments', departmentId);
    if (!dept || dept.status === 'Inactive') {
      return res.status(400).json({ message: 'Invalid or inactive department selected.' });
    }
  }

  const users = db.read('users');
  const employeeId = `AF-EMP-${String(users.length + 1).padStart(3, '0')}`;
  const hashedPassword = bcrypt.hashSync(password, 10);

  // Schema: users — id auto-generated by db.create; all columns listed below
  const newUser = db.create('users', {
    employeeId,
    name,
    email: email.toLowerCase(),
    password: hashedPassword,
    phone: phone || '',
    photo: '',
    departmentId: departmentId || '',
    role: 'Employee',     // Signup ALWAYS creates Employee — roles assigned by Admin only
    status: 'Active',
    joiningDate: new Date().toISOString().split('T')[0]
    // createdAt injected by db.create; updatedAt set on updates
  });

  logActivity('system', 'System', 'Signup', 'User', newUser.id, null, { email: newUser.email, name: newUser.name }, req);

  const token = jwt.sign({ id: newUser.id }, SECRET_KEY, { expiresIn: '7d' });
  const { password: _, ...userWithoutPassword } = newUser;
  res.status(201).json({ user: userWithoutPassword, token });
});

// Login
router.post('/login', (req, res) => {
  const { email, password } = req.body;

  if (!email || !password) {
    return res.status(400).json({ message: 'Email and password are required.' });
  }

  const user = db.findOne('users', { email: email.toLowerCase() });
  if (!user) {
    return res.status(400).json({ message: 'Invalid email or password.' });
  }

  if (user.status !== 'Active') {
    return res.status(403).json({ message: 'Your account is deactivated. Please contact your system Administrator.' });
  }

  const isMatch = bcrypt.compareSync(password, user.password);
  if (!isMatch) {
    return res.status(400).json({ message: 'Invalid email or password.' });
  }

  logActivity(user.id, user.name, 'Login', 'User', user.id, null, { action: 'logged_in' }, req);

  const token = jwt.sign({ id: user.id }, SECRET_KEY, { expiresIn: '7d' });
  const { password: _, ...userWithoutPassword } = user;
  res.json({ user: userWithoutPassword, token });
});

// Forgot Password (mock reset)
router.post('/forgot-password', (req, res) => {
  const { email } = req.body;

  if (!email) {
    return res.status(400).json({ message: 'Email address is required.' });
  }

  const user = db.findOne('users', { email: email.toLowerCase() });
  if (!user) {
    return res.status(400).json({ message: 'No account found with this email address.' });
  }

  const newHashedPassword = bcrypt.hashSync('temp123', 10);
  // updatedAt set by db.update automatically
  db.update('users', user.id, { password: newHashedPassword });

  logActivity('system', 'System', 'Forgot Password', 'User', user.id, null, { email: user.email }, req);

  res.json({
    message: 'Password has been reset to temporary credentials.',
    tempPassword: 'temp123'
  });
});

// Get current profile
router.get('/profile', auth, (req, res) => {
  const { password: _, ...userWithoutPassword } = req.user;
  res.json(userWithoutPassword);
});

// Get employee directory
// Admin & Asset Manager: all employees
// Department Head: only their own department
// Employee: only themselves
router.get('/employees', auth, (req, res) => {
  let employees = db.read('users').map(({ password, ...user }) => user);

  if (req.user.role === 'Employee') {
    // Employees can only see themselves
    employees = employees.filter(u => u.id === req.user.id);
  } else if (req.user.role === 'Department Head') {
    // Department Heads see their own department members
    employees = employees.filter(u => u.departmentId === req.user.departmentId);
  }
  // Admin and Asset Manager see everyone

  res.json(employees);
});

// Admin promotes employee role — only Admin can call this
router.put('/employees/:id/role', auth, checkRole(['Admin']), (req, res) => {
  const { id } = req.params;
  const { role } = req.body;

  const validRoles = ['Admin', 'Asset Manager', 'Department Head', 'Employee'];
  if (!validRoles.includes(role)) {
    return res.status(400).json({ message: 'Invalid role. Valid roles: ' + validRoles.join(', ') });
  }

  const employee = db.findById('users', id);
  if (!employee) {
    return res.status(404).json({ message: 'Employee not found.' });
  }

  // Prevent admin from revoking own admin role
  if (employee.id === req.user.id && role !== 'Admin') {
    return res.status(400).json({ message: 'You cannot revoke your own administrator role.' });
  }

  const original = { ...employee };
  const { updated } = db.update('users', id, { role });

  logActivity(req.user.id, req.user.name, 'Promote', 'User', id, original.role, role, req);

  // Schema: notifications — userId, message, type, link, isRead, timestamp
  db.create('notifications', {
    userId: id,
    message: `Your role has been updated to "${role}" by the Administrator.`,
    type: 'Role Promotion',
    link: '/dashboard',
    isRead: false,
    timestamp: new Date().toISOString()
  });

  const { password: _, ...employeeWithoutPassword } = updated;
  res.json(employeeWithoutPassword);
});

// Admin activate/deactivate employee status
router.put('/employees/:id/status', auth, checkRole(['Admin']), (req, res) => {
  const { id } = req.params;
  const { status } = req.body;

  if (status !== 'Active' && status !== 'Inactive') {
    return res.status(400).json({ message: 'Status must be Active or Inactive.' });
  }

  const employee = db.findById('users', id);
  if (!employee) {
    return res.status(404).json({ message: 'Employee not found.' });
  }

  if (employee.id === req.user.id) {
    return res.status(400).json({ message: 'You cannot deactivate your own account.' });
  }

  const original = { ...employee };
  const { updated } = db.update('users', id, { status });

  logActivity(req.user.id, req.user.name, status === 'Active' ? 'Reactivate' : 'Deactivate', 'User', id, original.status, status, req);

  const { password: _, ...employeeWithoutPassword } = updated;
  res.json(employeeWithoutPassword);
});

// Update own profile (or Admin updates anyone)
// Schema fields updatable: name, phone, departmentId, photo — all in users schema
router.put('/employees/:id', auth, (req, res) => {
  const { id } = req.params;
  const { name, phone, departmentId, photo } = req.body;

  // Only admins can update others; employees can only update themselves
  if (req.user.role !== 'Admin' && req.user.id !== id) {
    return res.status(403).json({ message: 'Unauthorized profile update request.' });
  }

  const employee = db.findById('users', id);
  if (!employee) {
    return res.status(404).json({ message: 'Employee profile not found.' });
  }

  // Validate department
  if (departmentId !== undefined && departmentId !== '') {
    const dept = db.findById('departments', departmentId);
    if (!dept) {
      return res.status(400).json({ message: 'Invalid department assignment.' });
    }
    if (dept.status === 'Inactive') {
      return res.status(400).json({ message: 'Cannot assign employee to an inactive department.' });
    }
  }

  const original = { ...employee };
  // Build update only with defined fields matching users schema
  const updateData = {};
  if (name !== undefined) updateData.name = name;
  if (phone !== undefined) updateData.phone = phone;
  if (departmentId !== undefined) updateData.departmentId = departmentId;
  if (photo !== undefined) updateData.photo = photo;

  if (Object.keys(updateData).length === 0) {
    return res.status(400).json({ message: 'No valid fields provided for update.' });
  }

  const { updated } = db.update('users', id, updateData);

  logActivity(req.user.id, req.user.name, 'Update Profile', 'User', id, original, updated, req);

  const { password: _, ...employeeWithoutPassword } = updated;
  res.json(employeeWithoutPassword);
});

module.exports = router;
